name: Generate PR Release Notes

on:
  pull_request:
    types: [opened, reopened, edited, synchronize] 

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read     
      pull-requests: write 
    steps:
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: "test tag"

      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: "${{ steps.notes.outputs.release-notes }}"
            });
